### ISSUE TITLE
Teachable Machine for Pose Project

### ISSUE THREAD

**Issue by roga76** [mjdargen/Teachable-Machine-Object-Detection#2]
Do you know an implementation on python for the Pose Project. It would be great to have such an solution. I have no idea how to implement it.

**Comment by mjdargen** [comment]
I do not. To my knowledge, the pose portion of Teachable Machine only generates and exports models for tensorflow.js. It would require a change to the way Teachable Machine works. There are easy ways to convert a keras model into a tensorflow.js model, but sadly not the other way around.

If you were interested in building a pose project in Python, you could check out the project below. Best of luck!

https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by roga76** [comment]
I already worked with openpose. My interest is in the Teachable machine part, means, to train within Teachable machine a pose model and export it into a python script

**Comment by mjdargen** [comment]
Yeah, that would require a change to Teachable Machine on Google's end to allow for the training of keras models for their pose project.
